#!/bin/sh

directory=$1

listed=`ls $directory`

for i in $listed; do
    if [ $i != ${i/.mp4/} ]; then
        
        mp4path="${directory}/${i}"
        webmpath=${mp4path/.mp4/.webm}

	echo $mp4path
	echo $webmpath


        if [ -f $webmpath ]; then
            echo "$webmpath already exists, skipping conversion"
        else
            ffmpeg -i $mp4path -f webm -vcodec libvpx_vp8 \
            -acodec libvorbis -ab 160000 -sameq $webmpath
        fi
    fi
done
