#!/usr/bin/env ruby

def convert( video_file )
    
    if video_file =~ /\.mp4|\.m4v/
        mpeg_movie = String.new(video_file)
        webm_movie = String.new(video_file)

        webm_movie[/\.mp4|\.m4v/] = '.webm'

        if File.exists?( webm_movie ) == false
            vpx_flag = 'libvpx'
        

            if RUBY_PLATFORM =~ /darwin/
                vpx_flag = 'libvpx_vp8'
            end

            system("ffmpeg -i #{mpeg_movie} -f webm -vcodec #{vpx_flag} \
            -acodec libvorbis -ab 160000 -sameq #{webm_movie}")
        end
    end
end


ARGV.each do |arg|
    if File.directory?( arg )
        Dir.foreach(arg) { |d| convert(arg + d) }
    else
        convert( arg )
    end
end
